version: '3.8'

services:
  laboratorio-euvwa:
    build: .
    container_name: euvwa_container
    ports:
      - "3000:3000"
    volumes:
      - ./src/public/uploads:/app/src/public/uploads
    environment:
      - NODE_ENV=production